version: "3.8"

services:
  blog:
    build:
      context: https://github.com/jcookin/blog.git
    image: blog:latest
    container_name: blog
    expose:
      - "80"
    deploy:
      replicas: 1
    restart: unless-stopped
    ports:
      - "3030:80"
    
networks:
  internal:

  