version: "3.8"

services:
  blog:
    build:
      # args:
      #   buildno: 1 ## TODO: increment build number in github action? & update Dockerfile to use
      context: https://github.com/jcookin/blog.git
      # dockerfile: Dockerfile
    image: blog:v1
    container_name: blog
    expose:
      - "80"
    deploy:
      replicas: 1
    restart: unless-stopped
    ports:
      - "3030:80"
    
networks:
  internal:

  