FROM arm64v8/rust:1-alpine3.18 as build

WORKDIR /workspace

# Install latest mdbook release
RUN wget -O mdbook-aarch64.tgz https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-aarch64-unknown-linux-musl.tar.gz
RUN tar -xzvf mdbook-aarch64.tgz -C /usr/bin/

COPY . .

RUN mdbook build -d /workspace/book

FROM nginx:alpine3.18-slim AS prod

COPY --from=build /workspace/book /usr/share/nginx/html