FROM arm64v8/rust:1-alpine3.18 as build

WORKDIR /workspace

# Install latest mdbook release
RUN cargo install --git https://github.com/rust-lang/mdBook.git mdbook

COPY . .

RUN mdbook build -d /workspace/book

FROM nginx:alpine3.18-slim AS prod

COPY --from=build /workspace/book /usr/share/nginx/html